services:

    Shapecode\Bundle\CronSonataAdminBundle\Admin\CronjobAdmin:
        arguments: [~, Shapecode\Bundle\CronBundle\Entity\CronJob, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cronjobs, group: Cronjobs }

    Shapecode\Bundle\CronSonataAdminBundle\Admin\CronjobResultAdmin:
        arguments: [~, Shapecode\Bundle\CronBundle\Entity\CronJobResult, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Results, group: Cronjobs }
